### ISSUE TITLE
premodel evalue problem

### ISSUE THREAD

**Issue by QingZhuanya** [autonomousvision/transfuser#160]
Hello, I get a problem when I run:

` ./leaderboard/scripts/local_evaluation.sh /home/qingzhuan/learning_base/imitation_learning/transfuser/carla /home/qingzhuan/learning_base/imitation_learning/transfuser`

get a worong output flowing:
```
/home/qingzhuan/learning_base/imitation_learning/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py:89: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(dist.version) < LooseVersion('0.9.10'):
Traceback (most recent call last):
  File "/home/qingzhuan/learning_base/imitation_learning/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py", line 466, in main
    leaderboard_evaluator = LeaderboardEvaluator(arguments, statistics_manager)
  File "/home/qingzhuan/learning_base/imitation_learning/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py", line 95, in __init__
    self.module_agent = importlib.import_module(module_name)
  File "/home/qingzhuan/miniconda3/envs/tfuse/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qingzhuan/learning_base/imitation_learning/transfuser/team_code_transfuser/submission_agent.py", line 15, in <module>
    from model import LidarCenterNet
  File "/home/qingzhuan/learning_base/imitation_learning/transfuser/team_code_transfuser/model.py", line 10, in <module>
    from point_pillar import PointPillarNet
  File "/home/qingzhuan/learning_base/imitation_learning/transfuser/team_code_transfuser/point_pillar.py", line 6, in <module>
    from torch_scatter import scatter_mean, scatter_max
  File "/home/qingzhuan/miniconda3/envs/tfuse/lib/python3.7/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/qingzhuan/miniconda3/envs/tfuse/lib/python3.7/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/qingzhuan/miniconda3/envs/tfuse/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/qingzhuan/miniconda3/envs/tfuse/lib/python3.7/site-packages/torch_scatter/_scatter_cpu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE
Exception ignored in: <function LeaderboardEvaluator.__del__ at 0x7fdc04673290>
Traceback (most recent call last):
  File "/home/qingzhuan/learning_base/imitation_learning/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py", line 122, in __del__
    self._cleanup()
  File "/home/qingzhuan/learning_base/imitation_learning/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py", line 134, in _cleanup
    if self.manager and self.manager.get_running_status() \
AttributeError: 'LeaderboardEvaluator' object has no attribute 'manager'
Traceback (most recent call last):
  File "/home/qingzhuan/learning_base/imitation_learning/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py", line 476, in <module>
    main()
  File "/home/qingzhuan/learning_base/imitation_learning/transfuser/leaderboard/leaderboard/leaderboard_evaluator_local.py", line 472, in main
    del leaderboard_evaluator
UnboundLocalError: local variable 'leaderboard_evaluator' referenced before assignment
```

could you give me some advise? thans!!!

**Comment by QingZhuanya** [comment]
I have solved this problem inspired by [https://github.com/autonomousvision/transfuser/issues/114]
take a note, with my conputer configuration(RTX3060):
```
cudatoolkit=11.3
torch-scatter=2.1.0+pt112cu113     
torchaudio=0.12.0+cu113    
torchvision=0.13.0+cu113     
```       

running step by step:

- in environment.yml change cudatoolkit=10.2 with cudatoolkit=11.3
- in team_code_transfuser/requirements.txt delete

```
torch==1.11.0
torchaudio==0.11.0
torchvision==0.12.0
```

- and then

```
conda activate tfuse
pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113
pip install --no-index torch-scatter -f https://data.pyg.org/whl/torch-1.12.0+cu113.html #will not produce garbled characters
pip install mmcv-full==1.6.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12.0/index.html #cuda and torch version need to  correspond one-to-one 
```
thanks!!!
