### ISSUE TITLE
Some problem about data generation

### ISSUE THREAD

**Issue by wanhaodong98** [autonomousvision/transfuser#19]
After I deployed the operating environment, i run the
./leaderboard/scripts/run_evaluation.sh without any modify
then have an error

Problem reading checkpoint. Route id 60 larger than maximum number of routes 23
========= Preparing RouteScenario_0 (repetition 0) =========
 \> Setting up the agent
routes_town01_short_10_01_00_37_02
\> Loading the world
\> Running the route
Traceback (most recent call last):
  File "/home/harli/transfuser-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 152, in _tick_scenario
    ego_action = self._agent()
  File "/home/harli/transfuser-main/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 82, in __call__
    return self._agent()
  File "/home/harli/transfuser-main/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 115, in __call__
    control = self.run_step(input_data, timestamp)
  File "leaderboard/team_code/auto_pilot.py", line 177, in run_step
    self.save(far_node, near_command, steer, throttle, brake, target_speed, data)
TypeError: save() missing 1 required positional argument: 'tick_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 477, in main
    leaderboard_evaluator.run(arguments)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 414, in run
    self._load_and_run_scenario(args, config)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 351, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/home/harli/transfuser-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 136, in run_scenario
    self._tick_scenario(timestamp)
  File "/home/harli/transfuser-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 159, in _tick_scenario
    raise AgentError(e)
leaderboard.autoagents.agent_wrapper.AgentError: save() missing 1 required positional argument: 'tick_data'

The server has an error after a few seconds

4.24.3-0+++UE4+Release-4.24 518 0
Disabling core dumps.
Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554 
CommonUnixCrashHandler: Signal=11
Malloc Size=65535 LargeMemoryPoolOffset=131119 
Malloc Size=111328 LargeMemoryPoolOffset=242464 
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)

I use the Ubuntu 20 and Nvidia1080Ti

**Comment by ap229997** [comment]
I updated the code. Try again and let me know if there are still some issues.

**Comment by wanhaodong98** [comment]
Thank you for your quickly reply, but there are still problem.
Problem reading checkpoint. Route id 60 larger than maximum number of routes 32

========= Preparing RouteScenario_0 (repetition 0) =========
\> Setting up the agent
routes_town05_short_10_01_02_38_08
\> Loading the world
\> Running the route
Traceback (most recent call last):
  File "/home/harli/transfuser-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 152, in _tick_scenario
    ego_action = self._agent()
  File "/home/harli/transfuser-main/leaderboard/leaderboard/autoagents/agent_wrapper.py", line 82, in __call__
    return self._agent()
  File "/home/harli/transfuser-main/leaderboard/leaderboard/autoagents/autonomous_agent.py", line 115, in __call__
    control = self.run_step(input_data, timestamp)
  File "leaderboard/team_code/auto_pilot.py", line 177, in run_step
    self.save(near_node, far_node, near_command, steer, throttle, brake, target_speed, data)
  File "/home/harli/transfuser-main/leaderboard/team_code/base_agent.py", line 303, in save
    'is_vehicle_present': self.is_vehicle_present,
AttributeError: 'AutoPilot' object has no attribute 'is_vehicle_present'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 477, in main
    leaderboard_evaluator.run(arguments)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 414, in run
    self._load_and_run_scenario(args, config)
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 351, in _load_and_run_scenario
    self.manager.run_scenario()
  File "/home/harli/transfuser-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 136, in run_scenario
    self._tick_scenario(timestamp)
  File "/home/harli/transfuser-main/leaderboard/leaderboard/scenarios/scenario_manager.py", line 159, in _tick_scenario
    raise AgentError(e)
leaderboard.autoagents.agent_wrapper.AgentError: 'AutoPilot' object has no attribute 'is_vehicle_present'

**Comment by ap229997** [comment]
Sorry, I think I missed a few things earlier when I pushed the code. I updated the code again.

**Comment by wanhaodong98** [comment]
Sorry, I think the file you modified has space errors. I fixed them, but there are still errors[![ImKGvf.md.png](https://s3.jpg.cm/2021/10/01/ImKGvf.md.png)](https://imagelol.com/image/ImKGvf)

**Comment by ap229997** [comment]
Thanks a lot for pointing this out. I just realized that I had updated `base_agent.py` at some point but forgot to update `auto_pilot.py`. Hopefully, the erros are fixed now.

**Comment by wanhaodong98** [comment]
Thank you again for your help. The program can run normally, but Carla frame rate is very low. Is that normal?

**Comment by ap229997** [comment]
Do you mean the CARLA server fps is low or the data generation rate is slow?

**Comment by wanhaodong98** [comment]
CARLA server fps is low.

**Comment by ap229997** [comment]
The server is run at 20 fps as per the leaderboard framework. This can be changed in [leaderboard_evaluator.py](https://github.com/autonomousvision/transfuser/blob/main/leaderboard/leaderboard/leaderboard_evaluator.py).

**Comment by wanhaodong98** [comment]
Thank your for your reply. This problem has been solved. I will close this issue.
