### ISSUE TITLE
ConvNext Backbone - AttributeError: 'ImageCNN' object has no attribute 'config'

### ISSUE THREAD

**Issue by animikhaich** [autonomousvision/transfuser#190]
Trying to train with any Architecture of ConvNext backbone leads to an error. The traceback is given below:
```
Traceback (most recent call last):
  File "train.py", line 757, in <module>
    main()
  File "/home/ani/miniconda3/envs/rlvn/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "train.py", line 297, in main
    bool(args.use_velocity),
  File "/home/ani/Projects/ADCIL-Sim2Real/transfuser/team_code_transfuser/model.py", line 565, in __init__
    self._model = TransfuserBackbone(config, image_architecture, lidar_architecture, use_velocity=use_velocity).to(self.device)
  File "/home/ani/Projects/ADCIL-Sim2Real/transfuser/team_code_transfuser/transfuser.py", line 22, in __init__
    self.image_encoder = ImageCNN(architecture=image_architecture, normalize=True)
  File "/home/ani/Projects/ADCIL-Sim2Real/transfuser/team_code_transfuser/transfuser.py", line 414, in __init__
    self.features.global_pool.norm = nn.LayerNorm((self.config.perception_output_features,1,1), _tmp.eps, _tmp.elementwise_affine)
  File "/home/ani/miniconda3/envs/rlvn/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1186, in __getattr__
    type(self).__name__, name))
AttributeError: 'ImageCNN' object has no attribute 'config'
```

Upon closer inspection, it seems to be an issue with the class ImageCNN. In particular [Line 414](https://github.com/autonomousvision/transfuser/blob/2022/team_code_transfuser/transfuser.py#L414). 

ImageCNN does not have "config" initialized. 

Update: Adding some more information. I used these arguments for training `--image_architecture convnext_base --lidar_architecture convnext_base`.

**Comment by Kait0** [comment]
Thanks, think I fixed the problem. Can you pull and try again?

**Comment by animikhaich** [comment]
Thanks. Yes. I was using an older commit. It has been fixed!
