### ISSUE TITLE
leaderboard error and manager have been define before

### ISSUE THREAD

**Issue by 830jz** [autonomousvision/transfuser#209]
# Create the ScenarioManager
        self.manager = ScenarioManager(args.timeout, args.debug > 1)

Traceback (most recent call last):
  File "D:\transfuser\transfuser\leaderboard\leaderboard\leaderboard_evaluator.py", line 122, in __del__
    self._cleanup()
  File "D:\transfuser\transfuser\leaderboard\leaderboard\leaderboard_evaluator.py", line 134, in _cleanup
    if self.manager and self.manager.get_running_status() \
AttributeError: 'LeaderboardEvaluator' object has no attribute 'manager'

**Comment by Kait0** [comment]
what exactly did you do, such that this error appears?
