### ISSUE TITLE
Issues During Evaluation

### ISSUE THREAD

**Issue by zyan003** [autonomousvision/transfuser#79]
Dear TransFuser Team,

I was trying to run evaluation with customized routes but encountered some error messages like this:

`> Registering the global statistics
Exception ignored in: <function LeaderboardEvaluator.__del__ at 0x7f90db186560>
Traceback (most recent call last):
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 124, in __del__
    self._cleanup()
  File "leaderboard/leaderboard/leaderboard_evaluator.py", line 157, in _cleanup
    self._agent_watchdog.stop()
  File "/home/zizheng/Documents/transfuser/scenario_runner/srunner/scenariomanager/watchdog.py", line 72, in stop
    self._timer.cancel()
AttributeError: 'NoneType' object has no attribute 'cancel'
`

Do you know what causes this issue and how to fix it?

Thanks in advance for your time and help!

**Comment by ap229997** [comment]
Try changing the results file path to something else.
https://github.com/autonomousvision/transfuser/blob/9d5ebf01f7b5f6e5c02ebe0cba423119c465b388/leaderboard/scripts/run_evaluation.sh#L21

**Comment by zyan003** [comment]
Thank you very much for replying. It works!
